// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colSumSq_dge
/* the following codes are from the R package bravo */ NumericVector colSumSq_dge(NumericVector x, IntegerVector dim);
RcppExport SEXP _geommc_colSumSq_dge(SEXP xSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumSq_dge(x, dim));
    return rcpp_result_gen;
END_RCPP
}
// colSumSq_matrix
NumericVector colSumSq_matrix(NumericMatrix x);
RcppExport SEXP _geommc_colSumSq_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumSq_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// colMSD_dgc
NumericVector colMSD_dgc(S4 mat, NumericVector m);
RcppExport SEXP _geommc_colMSD_dgc(SEXP matSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(colMSD_dgc(mat, m));
    return rcpp_result_gen;
END_RCPP
}
// colSUMIDX_dgc
NumericVector colSUMIDX_dgc(S4 mat);
RcppExport SEXP _geommc_colSUMIDX_dgc(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(colSUMIDX_dgc(mat));
    return rcpp_result_gen;
END_RCPP
}
// rw_mc_cpp
List rw_mc_cpp(Function log_target, NumericVector initial, int n_iter, SEXP sig, bool return_sample);
RcppExport SEXP _geommc_rw_mc_cpp(SEXP log_targetSEXP, SEXP initialSEXP, SEXP n_iterSEXP, SEXP sigSEXP, SEXP return_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type log_target(log_targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sample(return_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(rw_mc_cpp(log_target, initial, n_iter, sig, return_sample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geommc_colSumSq_dge", (DL_FUNC) &_geommc_colSumSq_dge, 2},
    {"_geommc_colSumSq_matrix", (DL_FUNC) &_geommc_colSumSq_matrix, 1},
    {"_geommc_colMSD_dgc", (DL_FUNC) &_geommc_colMSD_dgc, 2},
    {"_geommc_colSUMIDX_dgc", (DL_FUNC) &_geommc_colSUMIDX_dgc, 1},
    {"_geommc_rw_mc_cpp", (DL_FUNC) &_geommc_rw_mc_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_geommc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
