// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ldens_mvnorm
double ldens_mvnorm(SEXP y_sexp, SEXP mean_sexp, SEXP Sigma_sexp);
RcppExport SEXP _geommc_ldens_mvnorm(SEXP y_sexpSEXP, SEXP mean_sexpSEXP, SEXP Sigma_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mean_sexp(mean_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigma_sexp(Sigma_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(ldens_mvnorm(y_sexp, mean_sexp, Sigma_sexp));
    return rcpp_result_gen;
END_RCPP
}
// ldens_mvnormchol
double ldens_mvnormchol(SEXP y_sexp, SEXP mean_sexp, SEXP chol_sig_sexp);
RcppExport SEXP _geommc_ldens_mvnormchol(SEXP y_sexpSEXP, SEXP mean_sexpSEXP, SEXP chol_sig_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mean_sexp(mean_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chol_sig_sexp(chol_sig_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(ldens_mvnormchol(y_sexp, mean_sexp, chol_sig_sexp));
    return rcpp_result_gen;
END_RCPP
}
// rmvnorm
arma::vec rmvnorm(SEXP mu_sexp, SEXP Sigma_sexp);
RcppExport SEXP _geommc_rmvnorm(SEXP mu_sexpSEXP, SEXP Sigma_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mu_sexp(mu_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigma_sexp(Sigma_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvnorm(mu_sexp, Sigma_sexp));
    return rcpp_result_gen;
END_RCPP
}
// bc
arma::mat bc(SEXP mu1_sexp, SEXP mu2_sexp, SEXP sig1_sexp, SEXP sig2_sexp, bool diag_var);
RcppExport SEXP _geommc_bc(SEXP mu1_sexpSEXP, SEXP mu2_sexpSEXP, SEXP sig1_sexpSEXP, SEXP sig2_sexpSEXP, SEXP diag_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mu1_sexp(mu1_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mu2_sexp(mu2_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sig1_sexp(sig1_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sig2_sexp(sig2_sexpSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_var(diag_varSEXP);
    rcpp_result_gen = Rcpp::wrap(bc(mu1_sexp, mu2_sexp, sig1_sexp, sig2_sexp, diag_var));
    return rcpp_result_gen;
END_RCPP
}
// logp_vs_in_dense
double logp_vs_in_dense(IntegerVector model, const arma::mat& X, double yty, const arma::vec& Xty, double mult_c, double add_c, double lam, double logw);
RcppExport SEXP _geommc_logp_vs_in_dense(SEXP modelSEXP, SEXP XSEXP, SEXP ytySEXP, SEXP XtySEXP, SEXP mult_cSEXP, SEXP add_cSEXP, SEXP lamSEXP, SEXP logwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type yty(ytySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< double >::type mult_c(mult_cSEXP);
    Rcpp::traits::input_parameter< double >::type add_c(add_cSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type logw(logwSEXP);
    rcpp_result_gen = Rcpp::wrap(logp_vs_in_dense(model, X, yty, Xty, mult_c, add_c, lam, logw));
    return rcpp_result_gen;
END_RCPP
}
// logp_vs_in_sparse
double logp_vs_in_sparse(IntegerVector model, const arma::sp_mat& X, double yty, const arma::vec& Xty, double mult_c, double add_c, double lam, double logw);
RcppExport SEXP _geommc_logp_vs_in_sparse(SEXP modelSEXP, SEXP XSEXP, SEXP ytySEXP, SEXP XtySEXP, SEXP mult_cSEXP, SEXP add_cSEXP, SEXP lamSEXP, SEXP logwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type yty(ytySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< double >::type mult_c(mult_cSEXP);
    Rcpp::traits::input_parameter< double >::type add_c(add_cSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type logw(logwSEXP);
    rcpp_result_gen = Rcpp::wrap(logp_vs_in_sparse(model, X, yty, Xty, mult_c, add_c, lam, logw));
    return rcpp_result_gen;
END_RCPP
}
// colSumSq_dge
/* the following codes are from the R package bravo */ NumericVector colSumSq_dge(NumericVector x, IntegerVector dim);
RcppExport SEXP _geommc_colSumSq_dge(SEXP xSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumSq_dge(x, dim));
    return rcpp_result_gen;
END_RCPP
}
// colSumSq_matrix
NumericVector colSumSq_matrix(NumericMatrix x);
RcppExport SEXP _geommc_colSumSq_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumSq_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// colMSD_dgc
NumericVector colMSD_dgc(S4 mat, NumericVector m);
RcppExport SEXP _geommc_colMSD_dgc(SEXP matSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(colMSD_dgc(mat, m));
    return rcpp_result_gen;
END_RCPP
}
// colSUMIDX_dgc
NumericVector colSUMIDX_dgc(S4 mat);
RcppExport SEXP _geommc_colSUMIDX_dgc(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(colSUMIDX_dgc(mat));
    return rcpp_result_gen;
END_RCPP
}
// rwm
List rwm(Function log_target, NumericVector initial, int n_iter, SEXP sig, bool return_sample);
RcppExport SEXP _geommc_rwm(SEXP log_targetSEXP, SEXP initialSEXP, SEXP n_iterSEXP, SEXP sigSEXP, SEXP return_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type log_target(log_targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sample(return_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(rwm(log_target, initial, n_iter, sig, return_sample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geommc_ldens_mvnorm", (DL_FUNC) &_geommc_ldens_mvnorm, 3},
    {"_geommc_ldens_mvnormchol", (DL_FUNC) &_geommc_ldens_mvnormchol, 3},
    {"_geommc_rmvnorm", (DL_FUNC) &_geommc_rmvnorm, 2},
    {"_geommc_bc", (DL_FUNC) &_geommc_bc, 5},
    {"_geommc_logp_vs_in_dense", (DL_FUNC) &_geommc_logp_vs_in_dense, 8},
    {"_geommc_logp_vs_in_sparse", (DL_FUNC) &_geommc_logp_vs_in_sparse, 8},
    {"_geommc_colSumSq_dge", (DL_FUNC) &_geommc_colSumSq_dge, 2},
    {"_geommc_colSumSq_matrix", (DL_FUNC) &_geommc_colSumSq_matrix, 1},
    {"_geommc_colMSD_dgc", (DL_FUNC) &_geommc_colMSD_dgc, 2},
    {"_geommc_colSUMIDX_dgc", (DL_FUNC) &_geommc_colSUMIDX_dgc, 1},
    {"_geommc_rwm", (DL_FUNC) &_geommc_rwm, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_geommc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
