# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
ldens_mvnorm <- function(y_sexp, mean_sexp, Sigma_sexp) {
    .Call(`_geommc_ldens_mvnorm`, y_sexp, mean_sexp, Sigma_sexp)
}

ldens_mvnormchol <- function(y_sexp, mean_sexp, chol_sig_sexp) {
    .Call(`_geommc_ldens_mvnormchol`, y_sexp, mean_sexp, chol_sig_sexp)
}

rmvnorm <- function(mu_sexp, Sigma_sexp) {
    .Call(`_geommc_rmvnorm`, mu_sexp, Sigma_sexp)
}

bc <- function(mu1_sexp, mu2_sexp, sig1_sexp, sig2_sexp, diag_var) {
    .Call(`_geommc_bc`, mu1_sexp, mu2_sexp, sig1_sexp, sig2_sexp, diag_var)
}

logp_vs_in_dense <- function(model, X, yty, Xty, mult_c, add_c, lam, logw) {
    .Call(`_geommc_logp_vs_in_dense`, model, X, yty, Xty, mult_c, add_c, lam, logw)
}

logp_vs_in_sparse <- function(model, X, yty, Xty, mult_c, add_c, lam, logw) {
    .Call(`_geommc_logp_vs_in_sparse`, model, X, yty, Xty, mult_c, add_c, lam, logw)
}

colSumSq_dge <- function(x, dim) {
    .Call(`_geommc_colSumSq_dge`, x, dim)
}

colSumSq_matrix <- function(x) {
    .Call(`_geommc_colSumSq_matrix`, x)
}

colMSD_dgc <- function(mat, m) {
    .Call(`_geommc_colMSD_dgc`, mat, m)
}

colSUMIDX_dgc <- function(mat) {
    .Call(`_geommc_colSUMIDX_dgc`, mat)
}

rwm <- function(log_target, initial, n_iter, sig, return_sample = FALSE) {
    .Call(`_geommc_rwm`, log_target, initial, n_iter, sig, return_sample)
}

